name: CI/CD Security Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Semgrep (SAST)
        run: semgrep --config .semgrep.yml --json > semgrep.json

      - name: Start Flask app in background
        run: |
          nohup python app.py &
          sleep 5

      - name: Run DAST (simple curl fallback)
        run: |
          curl "http://127.0.0.1:5000/echo?msg=<script>alert(1)</script>" -o dast_response.html || true

      - name: Generate final report
        run: python report_generator.py semgrep.json "" dast_response.html report.html

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep.json
            dast_response.html
            report.html